/*
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements.  See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.
 * The ASF licenses this file to You under the Apache License, Version 2.0
 * (the "License"); you may not use this file except in compliance with
 * the License.  You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.apache.nifi.validation;

import org.apache.commons.lang3.builder.EqualsBuilder;
import org.apache.commons.lang3.builder.HashCodeBuilder;
import org.apache.nifi.flowanalysis.FlowAnalysisRuleType;

import java.util.StringJoiner;

/**
 * A result of a rule violation produced during a flow analysis
 */
public class RuleViolation {
    private final FlowAnalysisRuleType ruleType;
    private final String subjectId;
    private final String scope;
    private final String ruleId;
    private final String violationMessage;

    private boolean enabled;

    private boolean available;

    public RuleViolation(FlowAnalysisRuleType ruleType, String subjectId, String scope, String ruleId, String violationMessage) {
        this.ruleType = ruleType;
        this.subjectId = subjectId;
        this.scope = scope;
        this.ruleId = ruleId;
        this.violationMessage = violationMessage;
        this.enabled = true;
        this.available = true;
    }

    /**
     * @return the type of the rule that produced this violation
     */
    public FlowAnalysisRuleType getRuleType() {
        return ruleType;
    }

    /**
     * @return the id of the subject that violated the rule. Usually an id of a component but in case of a
     *  general violation a unique id is generated by the framework.
     */
    public String getSubjectId() {
        return subjectId;
    }

    /**
     * @return the scope of the analysis that produced this violation. The id of the component or the process group that was
     *  the subject of the analysis.
     */
    public String getScope() {
        return scope;
    }

    /**
     * @return the id of the rule that produced this violation
     */
    public String getRuleId() {
        return ruleId;
    }

    /**
     * @return the violation message
     */
    public String getViolationMessage() {
        return violationMessage;
    }

    /**
     * @return true if this violation should be in effect, false otherwise
     */
    public boolean isEnabled() {
        return enabled;
    }

    public void setEnabled(boolean enabled) {
        this.enabled = enabled;
    }

    /**
     * Used by the framework internally to manage lifecycle
     */
    public boolean isAvailable() {
        return available;
    }

    public void setAvailable(boolean available) {
        this.available = available;
    }

    @Override
    public String toString() {
        return new StringJoiner(", ", RuleViolation.class.getSimpleName() + "[", "]")
            .add("ruleType=" + ruleType)
            .add("subjectId='" + subjectId + "'")
            .add("scope='" + scope + "'")
            .add("ruleId='" + ruleId + "'")
            .add("violationMessage='" + violationMessage + "'")
            .add("enabled=" + enabled)
            .add("available=" + available)
            .toString();
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;

        if (o == null || getClass() != o.getClass()) return false;

        RuleViolation that = (RuleViolation) o;

        return new EqualsBuilder()
            .append(enabled, that.enabled)
            .append(available, that.available)
            .append(ruleType, that.ruleType)
            .append(subjectId, that.subjectId)
            .append(scope, that.scope)
            .append(ruleId, that.ruleId)
            .append(violationMessage, that.violationMessage)
            .isEquals();
    }

    @Override
    public int hashCode() {
        return new HashCodeBuilder(17, 37)
            .append(ruleType)
            .append(subjectId)
            .append(scope)
            .append(ruleId)
            .append(violationMessage)
            .append(enabled)
            .append(available)
            .toHashCode();
    }
}
